# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamedlg.ui'
#
# Created: Wed May 16 23:34:22 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_GameDlgUI(object):
    def setupUi(self, GameDlgUI):
        GameDlgUI.setObjectName("GameDlgUI")
        GameDlgUI.resize(642, 518)
        self.verticalLayout_3 = QtGui.QVBoxLayout(GameDlgUI)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layout_img = QtGui.QHBoxLayout()
        self.layout_img.setObjectName("layout_img")
        self.picture = QtGui.QGraphicsView(GameDlgUI)
        self.picture.setObjectName("picture")
        self.layout_img.addWidget(self.picture)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_img.addItem(spacerItem)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_tags = QtGui.QPushButton(GameDlgUI)
        self.edit_tags.setObjectName("edit_tags")
        self.gridLayout_2.addWidget(self.edit_tags, 0, 1, 1, 1)
        self.labtags = QtGui.QLabel(GameDlgUI)
        self.labtags.setObjectName("labtags")
        self.gridLayout_2.addWidget(self.labtags, 0, 0, 1, 1)
        self.show_tags = QtGui.QListWidget(GameDlgUI)
        self.show_tags.setObjectName("show_tags")
        self.gridLayout_2.addWidget(self.show_tags, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.layout_img.addLayout(self.gridLayout_2)
        self.layout_img.setStretch(0, 8)
        self.layout_img.setStretch(1, 1)
        self.layout_img.setStretch(2, 3)
        self.verticalLayout_3.addLayout(self.layout_img)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labimg = QtGui.QLabel(GameDlgUI)
        self.labimg.setObjectName("labimg")
        self.gridLayout.addWidget(self.labimg, 0, 0, 1, 1)
        self.img = QtGui.QLineEdit(GameDlgUI)
        self.img.setObjectName("img")
        self.gridLayout.addWidget(self.img, 0, 1, 1, 1)
        self.labtitle = QtGui.QLabel(GameDlgUI)
        self.labtitle.setObjectName("labtitle")
        self.gridLayout.addWidget(self.labtitle, 1, 0, 1, 1)
        self.title = QtGui.QLineEdit(GameDlgUI)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 1, 1, 1)
        self.labfch = QtGui.QLabel(GameDlgUI)
        self.labfch.setObjectName("labfch")
        self.gridLayout.addWidget(self.labfch, 2, 0, 1, 1)
        self.franchise = QtGui.QComboBox(GameDlgUI)
        self.franchise.setObjectName("franchise")
        self.gridLayout.addWidget(self.franchise, 2, 1, 1, 1)
        self.labyear = QtGui.QLabel(GameDlgUI)
        self.labyear.setObjectName("labyear")
        self.gridLayout.addWidget(self.labyear, 3, 0, 1, 1)
        self.year = QtGui.QLineEdit(GameDlgUI)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 3, 1, 1, 1)
        self.labvote = QtGui.QLabel(GameDlgUI)
        self.labvote.setObjectName("labvote")
        self.gridLayout.addWidget(self.labvote, 4, 0, 1, 1)
        self.vote = QtGui.QLineEdit(GameDlgUI)
        self.vote.setObjectName("vote")
        self.gridLayout.addWidget(self.vote, 4, 1, 1, 1)
        self.labpriority = QtGui.QLabel(GameDlgUI)
        self.labpriority.setObjectName("labpriority")
        self.gridLayout.addWidget(self.labpriority, 5, 0, 1, 1)
        self.priority = QtGui.QLineEdit(GameDlgUI)
        self.priority.setObjectName("priority")
        self.gridLayout.addWidget(self.priority, 5, 1, 1, 1)
        self.labnote = QtGui.QLabel(GameDlgUI)
        self.labnote.setObjectName("labnote")
        self.gridLayout.addWidget(self.labnote, 6, 0, 1, 1)
        self.note = QtGui.QTextEdit(GameDlgUI)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit = QtGui.QPushButton(GameDlgUI)
        self.edit.setObjectName("edit")
        self.horizontalLayout.addWidget(self.edit)
        self.cancel = QtGui.QPushButton(GameDlgUI)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.scrollArea = QtGui.QScrollArea(GameDlgUI)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -123, 327, 472))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b01 = SplatButton(self.scrollAreaWidgetContents)
        self.b01.setMinimumSize(QtCore.QSize(0, 40))
        self.b01.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b01.setText("")
        self.b01.setObjectName("b01")
        self.verticalLayout.addWidget(self.b01)
        self.b02 = SplatButton(self.scrollAreaWidgetContents)
        self.b02.setMinimumSize(QtCore.QSize(0, 40))
        self.b02.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b02.setText("")
        self.b02.setObjectName("b02")
        self.verticalLayout.addWidget(self.b02)
        self.b03 = SplatButton(self.scrollAreaWidgetContents)
        self.b03.setMinimumSize(QtCore.QSize(0, 40))
        self.b03.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b03.setText("")
        self.b03.setObjectName("b03")
        self.verticalLayout.addWidget(self.b03)
        self.b04 = SplatButton(self.scrollAreaWidgetContents)
        self.b04.setMinimumSize(QtCore.QSize(0, 40))
        self.b04.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b04.setText("")
        self.b04.setObjectName("b04")
        self.verticalLayout.addWidget(self.b04)
        self.b05 = SplatButton(self.scrollAreaWidgetContents)
        self.b05.setMinimumSize(QtCore.QSize(0, 40))
        self.b05.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b05.setText("")
        self.b05.setObjectName("b05")
        self.verticalLayout.addWidget(self.b05)
        self.b06 = SplatButton(self.scrollAreaWidgetContents)
        self.b06.setMinimumSize(QtCore.QSize(0, 40))
        self.b06.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b06.setText("")
        self.b06.setObjectName("b06")
        self.verticalLayout.addWidget(self.b06)
        self.b07 = SplatButton(self.scrollAreaWidgetContents)
        self.b07.setMinimumSize(QtCore.QSize(0, 40))
        self.b07.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b07.setText("")
        self.b07.setObjectName("b07")
        self.verticalLayout.addWidget(self.b07)
        self.b08 = SplatButton(self.scrollAreaWidgetContents)
        self.b08.setMinimumSize(QtCore.QSize(0, 40))
        self.b08.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b08.setText("")
        self.b08.setObjectName("b08")
        self.verticalLayout.addWidget(self.b08)
        self.b09 = SplatButton(self.scrollAreaWidgetContents)
        self.b09.setMinimumSize(QtCore.QSize(0, 40))
        self.b09.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b09.setText("")
        self.b09.setObjectName("b09")
        self.verticalLayout.addWidget(self.b09)
        self.b10 = SplatButton(self.scrollAreaWidgetContents)
        self.b10.setMinimumSize(QtCore.QSize(0, 40))
        self.b10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.b10.setText("")
        self.b10.setObjectName("b10")
        self.verticalLayout.addWidget(self.b10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 5)

        self.retranslateUi(GameDlgUI)
        QtCore.QMetaObject.connectSlotsByName(GameDlgUI)

    def retranslateUi(self, GameDlgUI):
        GameDlgUI.setWindowTitle(QtGui.QApplication.translate("GameDlgUI", "Game Details", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_tags.setText(QtGui.QApplication.translate("GameDlgUI", "Edit tags", None, QtGui.QApplication.UnicodeUTF8))
        self.labtags.setText(QtGui.QApplication.translate("GameDlgUI", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.labimg.setText(QtGui.QApplication.translate("GameDlgUI", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.labtitle.setText(QtGui.QApplication.translate("GameDlgUI", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.labfch.setText(QtGui.QApplication.translate("GameDlgUI", "Franchise:", None, QtGui.QApplication.UnicodeUTF8))
        self.labyear.setText(QtGui.QApplication.translate("GameDlgUI", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.labvote.setText(QtGui.QApplication.translate("GameDlgUI", "Vote:", None, QtGui.QApplication.UnicodeUTF8))
        self.labpriority.setText(QtGui.QApplication.translate("GameDlgUI", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.labnote.setText(QtGui.QApplication.translate("GameDlgUI", "Note:", None, QtGui.QApplication.UnicodeUTF8))
        self.edit.setText(QtGui.QApplication.translate("GameDlgUI", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("GameDlgUI", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from gui.splatbtn import SplatButton
